aliyun:
     oss:
       accessKeyId: LTAIyaw3s6ajUgNN
       accessKeySecret: tQrppHDVGfkBYG8ccCFXKrmoInCz9k
       endpoint: oss-cn-shanghai.aliyuncs.com
       domain: http://fmsbb.oss-cn-shanghai.aliyuncs.com/
